### ISSUE TITLE
Illegal hardware instruction (core dumped)

### ISSUE THREAD

**Issue by oubrax** [SnowballSH/RustGlacier#11]
```rust
REPL for Glacier 2.0 dev
> 1312
#>> 1312
> 1 + 1
[1]    34675 illegal hardware instruction (core dumped)  cargo run
```
This problem occurred in my linux machine (arch linux) when doing more than 2 or more expressions

**Comment by SnowballSH** [comment]
This works perfectly on my machine. I don't know why illegal instruction is happening.
Thanks for the issue and I will look into it.

**Comment by oubrax** [comment]
No problem, i just tried to open the lang take a look on it, i think the illegal instruction thing is a bug in the repl

**Comment by SnowballSH** [comment]
```
REPL for Glacier 2.0 dev
> 1312
#>> 1312
> 1 + 1
#>> 2
```
Cannot reproduce on a fresh linux container.
